Update docker repository with latest changes

diff --git a/docker/opencog/atomspace-py/Dockerfile b/docker/opencog/atomspace-py/Dockerfile
--- a/docker/opencog/atomspace-py/Dockerfile
+++ b/docker/opencog/atomspace-py/Dockerfile
@@ -7,7 +7,9 @@
 # 3. docker start -i atompy
 #
 #
-FROM opencog/atomspace:latest
+ARG OS_VERSION=latest
+ARG BASE_IMAGE=opencog/atomspace:${OS_VERSION}
+FROM ${BASE_IMAGE}
 
 # Install Debian-managed packages to get base python abilities.
 RUN apt-get -y update && apt-get -y upgrade && apt-get -y autoremove
@@ -37,7 +39,10 @@ RUN .venv/bin/pip install uv
 RUN .venv/bin/pip install requests
 
 # Model Context Protocol MCP python sdk
-RUN .venv/bin/pip install mcp
+# This SDK is not available on older OS'es, so just || true so that
+# the Docker build does not fail. Of course, its a silent failure, but
+# who cares. No one will be using it.
+RUN .venv/bin/pip install mcp || true
 
 # Opencog installed itself here; we want it available in the venv.
 ENV PYTHONPATH=/usr/local/lib/python3.12/dist-packages:$PYTHONPATH
